const express=require('express')
const server=express()
const bp=require('body-parser')
server.use(bp.json())
const addflight = require('./routes/createflight')
server.use('/',addflight)
const bookticket =require('./routes/ticketbook')
server.use('/',bookticket)
const flightdetail = require('./routes/flightdetail')
server.use('/',flightdetail)
server.listen(3001,()=>console.log('server started'))
